<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(array('M_Login_Admin'));
        $this->load->library('form_validation');
        $this->load->library('template');
        $this->load->library('session');
        $this->load->helper('url');
        $this->load->helper('html');
    }


    public function index() 
    {
        $this->load->view('Admin/Login');

    }

    public function aksi_login(){
        $this->_rules();

        $username = $this->input->post('username');
        $password = $this->input->post('password');


        if ($this->form_validation->run() == FALSE) {
            redirect(base_url("Admin")); 
        }
        else{

        $data = array(
            'username' => $username,
            'password' => $password
            );

        $cek = $this->M_Login_Admin->cek_login_admin($data);
        if($cek > 0){

            $data_session = array(
                'username' => $username,
                );

            $this->session->set_userdata($data_session);

                redirect(base_url("C_DataUmkm")); 
            }


        else{
            $this->session->set_flashdata('message','(<span class="text-danger">Email atau Password anda salah ! ) <br> Silahkan Coba Lagi');
            redirect(base_url("Admin"));
        }
    }
}
    
    
    // Logout di sini
    public function logout() {
        session_destroy();
        redirect(base_url("Admin")); 

    }   

    public function _rules() 
    {
	$this->form_validation->set_rules('username', 'username', 'trim|required');
	
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }


}

/* End of file C_DataUmkm.php */
/* Location: ./application/controllers/C_DataUmkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:54:52 */
/* http://harviacode.com */