<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_Jenis_usaha extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_Jenis_usaha');
        $this->load->library('form_validation');
        $this->load->library('template');
        $this->load->helper('url');
        $this->load->helper('html');
    }

    public function index()
    {
        $c_jenis_usaha = $this->M_Jenis_usaha->get_all();

        $data = array(
            'c_jenis_usaha_data' => $c_jenis_usaha
        );

        $this->template->display('c_jenis_usaha/jenis_usaha_list', $data);
    }


    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_jenis_usaha/create_action'),
	    'id_jenis_usaha' => set_value('id_jenis_usaha'),
	    'nama_jenis_usaha' => set_value('nama_jenis_usaha'),
	);
        $this->template->display('c_jenis_usaha/jenis_usaha_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_jenis_usaha' => $this->input->post('nama_jenis_usaha',TRUE),
	    );

            $this->M_Jenis_usaha->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('c_jenis_usaha'));
        }
    }

    
    
    public function delete($id) 
    {
        $row = $this->M_Jenis_usaha->get_by_id($id);

        if ($row) {
            $this->M_Jenis_usaha->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('c_jenis_usaha'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_jenis_usaha'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_jenis_usaha', 'nama jenis usaha', 'trim|required');

	$this->form_validation->set_rules('id_jenis_usaha', 'id_jenis_usaha', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_Jenis_usaha.php */
/* Location: ./application/controllers/C_Jenis_usaha.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-05 21:46:19 */
/* http://harviacode.com */