<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_Kelurahan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_Kelurahan');
        $this->load->library('form_validation');
        $this->load->library('template');
        $this->load->helper('url');
        $this->load->helper('html');
    }

    public function index()
    {
        $c_kelurahan = $this->M_Kelurahan->get_all();

        $data = array(
            'c_kelurahan_data' => $c_kelurahan
        );

        $this->template->display('c_kelurahan/kelurahan_list', $data);
    }


    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_kelurahan/create_action'),
	    'id_kelurahan' => set_value('id_kelurahan'),
	    'nama_kelurahan' => set_value('nama_kelurahan'),
	    'nama_kecamatan' => set_value('nama_kecamatan'),
	);
        $this->template->display('c_kelurahan/kelurahan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kelurahan' => $this->input->post('nama_kelurahan',TRUE),
		'nama_kecamatan' => $this->input->post('nama_kecamatan',TRUE),
	    );

            $this->M_Kelurahan->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('c_kelurahan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->M_Kelurahan->get_by_id($id);

        if ($row) {
            $this->M_Kelurahan->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('c_kelurahan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_kelurahan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kelurahan', 'nama kelurahan', 'trim|required');
	$this->form_validation->set_rules('nama_kecamatan', 'nama kecamatan', 'trim|required');

	$this->form_validation->set_rules('id_kelurahan', 'id_kelurahan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_Kelurahan.php */
/* Location: ./application/controllers/C_Kelurahan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-13 04:27:57 */
/* http://harviacode.com */