<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_DataUsaha extends CI_Model
{

    public $table = 'data_usaha';
    public $id = 'id_umkm';
    public $id_data_usaha = 'id_data_usaha';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($id)
    {
        $this->db->order_by($this->id, $id);
        return $this->db->get($this->table)->result();

    }

    // get data by id
    function get_by_id($id)//untuk read
    {
       $this->db->where($this->id, $id);
        return $this->db->get($this->table)->result();
    }

    function get_by_id_data_usaha($id_data_usaha)//untuk update
    {
       $this->db->where($this->id_data_usaha, $id_data_usaha);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_data_usaha', $q);
	$this->db->or_like('id_umkm', $q);
	$this->db->or_like('kapasitas_produk', $q);
	$this->db->or_like('asset', $q);
	$this->db->or_like('omset', $q);
	$this->db->or_like('tenaga_wanita', $q);
	$this->db->or_like('tenaga_laki', $q);
	$this->db->or_like('pemasaran_dalam', $q);
	$this->db->or_like('pemasaran_luar', $q);
	$this->db->or_like('tahun', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_data_usaha', $q);
	$this->db->or_like('id_umkm', $q);
	$this->db->or_like('kapasitas_produk', $q);
	$this->db->or_like('asset', $q);
	$this->db->or_like('omset', $q);
	$this->db->or_like('tenaga_wanita', $q);
	$this->db->or_like('tenaga_laki', $q);
	$this->db->or_like('pemasaran_dalam', $q);
	$this->db->or_like('pemasaran_luar', $q);
	$this->db->or_like('tahun', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id_data_usaha, $data)
    {
        $this->db->where($this->id_data_usaha, $id_data_usaha);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id_data_usaha)
    {
        $this->db->where($this->id_data_usaha, $id_data_usaha);
        $this->db->delete($this->table);
    }

}

/* End of file M_DataUsaha.php */
/* Location: ./application/models/M_DataUsaha.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:56:36 */
/* http://harviacode.com */